[package]
name = "updock"
version = "0.1.0"
authors = ["Y0hy0h <Y0hy0h@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
regex = { version="1.3.1", default-features=false, features=["std", "perf"] }
reqwest = "0.9.22"
serde = "1.0.104"
log = "0.4.8"
env_logger = "0.7.1"
structopt = "0.3.5"
itertools = "0.8.2"
lazy_static = "1.4.0"
anyhow = "1.0.25"
thiserror = "1.0.9"
serde_json = "1.0.44"
serde_yaml = "0.8.11"
indexmap = { version = "1.3.0", features = ["serde-1"] }

[dev-dependencies]
proptest = "0.9.4"
