[package]
name = "updock"
version = "0.1.0"
authors = ["Y0hy0h <Y0hy0h@users.noreply.github.com>"]
edition = "2018"

[dependencies]
regex = { version="1.3.1", default-features=false, features=["std", "perf"] }

[dev-dependencies]
proptest = "0.9.4"
