[package]
name = "updock"
version = "0.1.0"
authors = ["Y0hy0h <Y0hy0h@users.noreply.github.com>"]
edition = "2018"

[dependencies]
regex = { version="1.3.1", default-features=false, features=["std", "perf"] }
reqwest = "0.9.22"
serde = "1.0.103"
log = "0.4.8"
env_logger = "0.7.1"
chrono = { version = "0.4.10", features = ["serde"] }
structopt = "0.3.5"
itertools = "0.8.2"

[dev-dependencies]
proptest = "0.9.4"
